"use server";
import { redirect } from "next/navigation";
import { requireAdmin, requireAnyRole } from "@/lib/admin-auth";
function v(f:FormData,n:string,m=5000){const x=f.get(n);return typeof x==="string"?x.trim().slice(0,m):""}
function go(p:string,e?:string){redirect(e?p+"?error="+e:p+"?saved=1")}
export async function createResearchPost(f:FormData){const {supabase,profile}=await requireAdmin();requireAnyRole(["super_admin","team_lead","technical_lead","media"],profile.role);const title=v(f,"title",220),slug=v(f,"slug",120).toLowerCase(),excerpt=v(f,"excerpt",500),body=v(f,"body",12000),category=v(f,"category",120);if(!title||!slug||!excerpt||!body||!category)go("/admin/research","missing");const {error}=await supabase.from("research_posts").insert({title,slug,excerpt,body,category,publish_status:"draft",visibility:"public"});if(error){console.error(error);go("/admin/research","save")}go("/admin/research")}
export async function createGalleryItem(f:FormData){const {supabase,profile}=await requireAdmin();requireAnyRole(["super_admin","team_lead","media"],profile.role);const title=v(f,"title",220),category=v(f,"category",120),source_type=v(f,"source_type",20),source_url=v(f,"source_url",1200),alt_text=v(f,"alt_text",300);if(!title||!category||!source_url||!alt_text||!["image","youtube"].includes(source_type))go("/admin/gallery","missing");const {error}=await supabase.from("gallery_items").insert({title,category,source_type,source_url,alt_text,publish_status:"draft",visibility:"public"});if(error){console.error(error);go("/admin/gallery","save")}go("/admin/gallery")}
export async function createSponsor(f:FormData){const {supabase,profile}=await requireAdmin();requireAnyRole(["super_admin","team_lead"],profile.role);const name=v(f,"name",180);if(!name)go("/admin/sponsors","missing");const {error}=await supabase.from("sponsors").insert({name,partnership_type:v(f,"partnership_type",120)||null,logo_url:v(f,"logo_url",1200)||null,website_url:v(f,"website_url",1200)||null,description:v(f,"description",1200)||null,publish_status:"draft",visibility:"public"});if(error){console.error(error);go("/admin/sponsors","save")}go("/admin/sponsors")}
export async function updateContactMessage(f:FormData){const {supabase,profile}=await requireAdmin();requireAnyRole(["super_admin","team_lead","hr_operations","media"],profile.role);const id=v(f,"id",80),status=v(f,"status",40);if(!/^[0-9a-f-]{36}$/i.test(id)||!["New","In Progress","Resolved"].includes(status))go("/admin/messages","invalid");const {error}=await supabase.from("contact_messages").update({status,handled_by:status==="Resolved"?profile.id:null,handled_at:status==="Resolved"?new Date().toISOString():null}).eq("id",id);if(error)go("/admin/messages","save");go("/admin/messages")}
