import Link from "next/link";

const stats=[["12+","Robots Built"],["25+","National Awards"],["5+","International Participations"],["40+","Team Members"]];
const robots=["BattleBot","Soccer Bot","Sumo Robot","Autonomous Robot","Drone","Robotic Boat"];

export default function Home(){return <main className="min-h-screen overflow-hidden">
  <header className="border-b border-white/10 bg-[#07111f]/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/" className="text-lg font-bold tracking-[.18em]">TEAM STELLAR</Link><nav className="hidden gap-7 text-sm text-slate-300 md:flex"><Link href="#robots">Robots</Link><Link href="#achievements">Achievements</Link><Link href="#team">Team</Link><Link href="#research">Research</Link><Link href="#sponsors">Sponsors</Link><Link href="#contact">Contact</Link></nav><Link href="#contact" className="rounded-full border border-[#19d3ff]/40 px-4 py-2 text-sm font-semibold text-white">Partner With Us</Link></div></header>
  <section className="relative"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(20,121,255,.22),transparent_35%),radial-gradient(circle_at_30%_70%,rgba(25,211,255,.10),transparent_30%)]"/><div className="relative mx-auto grid min-h-[78vh] max-w-7xl items-center gap-12 px-6 py-24 lg:grid-cols-[1.15fr_.85fr]"><div><p className="mb-5 text-sm font-semibold uppercase tracking-[.3em] text-[#19d3ff]">BRAC University Robotics Team</p><h1 className="max-w-4xl text-5xl font-black tracking-tight sm:text-6xl lg:text-8xl">Engineering Robots.<br/><span className="text-[#19d3ff]">Competing Beyond Borders.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Team Stellar builds, tests and competes with robotics systems across mechanical, embedded, software and autonomous engineering.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#robots" className="rounded-full bg-[#1479ff] px-6 py-3 font-semibold">Explore Our Robots</Link><Link href="#achievements" className="rounded-full border border-white/15 px-6 py-3 font-semibold">View Achievements</Link></div></div><div className="aspect-[4/5] rounded-3xl border border-white/10 bg-[linear-gradient(135deg,#102033,#07111f)] p-5 shadow-2xl"><div className="flex h-full items-end rounded-2xl border border-white/5 bg-[radial-gradient(circle_at_50%_40%,rgba(25,211,255,.16),transparent_35%)] p-6"><div><p className="text-xs uppercase tracking-[.25em] text-slate-400">Team Stellar</p><p className="mt-2 text-2xl font-bold">Real engineering. Real competition.</p><p className="mt-3 text-sm text-slate-400">Replace this visual panel with verified team/robot footage when media assets are available.</p></div></div></div></div></section>
  <section className="border-y border-white/10 bg-[#0b1727]"><div className="mx-auto grid max-w-7xl grid-cols-2 px-6 py-10 md:grid-cols-4">{stats.map(([n,l])=><div key={l} className="border-white/10 px-5 py-5 first:border-0 md:border-l"><div className="text-4xl font-black">{n}</div><div className="mt-2 text-sm text-slate-400">{l}</div></div>)}</div></section>
  <section id="robots" className="mx-auto max-w-7xl px-6 py-24"><p className="text-sm font-semibold uppercase tracking-[.25em] text-[#19d3ff]">Engineering Archive</p><h2 className="mt-3 text-4xl font-bold">Featured Robots</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{robots.map((r,i)=><article key={r} className="group rounded-2xl border border-white/10 bg-[#0b1727] p-6 transition hover:-translate-y-1 hover:border-[#19d3ff]/40"><div className="flex aspect-[16/10] items-end rounded-xl bg-[linear-gradient(135deg,#14253a,#08111d)] p-5"><span className="text-xs uppercase tracking-[.2em] text-slate-500">Robot media {String(i+1).padStart(2,"0")}</span></div><h3 className="mt-5 text-xl font-bold">{r}</h3><p className="mt-2 text-sm text-slate-400">Technical specification, development history and competition record.</p><Link href="/robots" className="mt-5 inline-block text-sm font-semibold text-[#19d3ff]">View Details →</Link></article>)}</div></section>
  <section id="achievements" className="border-y border-white/10 bg-[#0b1727]"><div className="mx-auto max-w-7xl px-6 py-24"><p className="text-sm font-semibold uppercase tracking-[.25em] text-[#19d3ff]">Proof, not claims</p><h2 className="mt-3 text-4xl font-bold">Recent Achievements</h2><p className="mt-5 max-w-2xl text-slate-400">Every published competition record will carry structured evidence such as certificates, official result sources and event media.</p></div></section>
  <section id="team" className="mx-auto max-w-7xl px-6 py-24"><h2 className="text-4xl font-bold">Built by Engineers</h2><p className="mt-4 max-w-2xl text-slate-400">Mechanical Design · Electronics & Embedded Systems · Software & AI · Control & Automation · Manufacturing · Media · Operations</p></section>
  <section id="research" className="border-y border-white/10 bg-[#0b1727]"><div className="mx-auto max-w-7xl px-6 py-24"><h2 className="text-4xl font-bold">Research & Knowledge</h2><p className="mt-4 max-w-2xl text-slate-400">Development reports, technical articles, competition post-mortems, AI vision experiments and engineering knowledge will live here.</p></div></section>
  <section id="sponsors" className="mx-auto max-w-7xl px-6 py-24"><h2 className="text-4xl font-bold">Support Bangladesh’s Next Generation of Robotics Competitors.</h2><p className="mt-5 max-w-2xl text-slate-400">A dedicated partnership platform will connect Team Stellar with sponsors, technology partners and international opportunities.</p><Link href="#contact" className="mt-8 inline-block rounded-full bg-[#ff7a00] px-6 py-3 font-bold">Become a Partner</Link></section>
  <footer id="contact" className="border-t border-white/10 bg-[#050c15]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-6 py-10 md:flex-row md:items-center md:justify-between"><div><div className="font-bold tracking-[.18em]">TEAM STELLAR</div><p className="mt-2 text-sm text-slate-500">BRAC University Robotics Team</p></div><div className="text-sm text-slate-500">Professional robotics. Documented engineering. Global ambition.</div></div></footer>
</main>}
